launch:
  ros__parameters:
    joy: true
    log_level: 10

/**:  # Wildcard (ここのパラメータは全てのnodeが読める<-名前に注意)
  ros__parameters:
    # Linear velocity[m/s], acceleration[m/s^2], deceleration[-m/s^2], jerk[m/s^3]
    linear_max:
      vel: 0.5
      acc: 5.0
      jer: 0.0
    # Angular velocity[deg/s], acceleration[deg/s^2], deceleration[-deg/s^2], jerk[deg/s^3]
    angular_max:
      vel: 90.0
      acc: 240.0
      jer: 0.0

chassis_driver_node:
  ros__parameters:
    wheel_radius : 0.03 # 車輪半径[m]
    attached_direction : 0.1928427125 # 車輪の取り付け半径[m]
    stop_canid : 0x100
    restart_canid : 0x101
    velocity_canid : 0x108
    linear_max_vel: 1.0 # 最大並進速度[m/s]
    angular_max_vel: 60.0 # 最大回転速度[deg/s]

socketcan_interface_node:
  ros__parameters:
    if_name : "can0"  # sokcetcanのネットワークデバイス名

onigokko_node:
 ros__parameters:
  dummy_parameter: 0.0